### ISSUE TITLE
Add spellcheck status check

### ISSUE THREAD

**Issue by mpetrunic** [ethereum/beacon-APIs#193]
Similar to execution api: https://github.com/ethereum/execution-apis/blob/main/.github/workflows/spellcheck.yaml

**Comment by staccDOTsol** [comment]
Certainly! To add a spellcheck status check to your Ethereum project, you can follow a similar approach as the execution API repository. Here's a step-by-step guide:

1. Create a new file named `.github/workflows/spellcheck.yaml` in the root directory of your Ethereum project.

2. Open the `spellcheck.yaml` file and add the following content:

```yaml
name: Spellcheck

on:
  pull_request:
    branches:
      - main

jobs:
  spellcheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Run spellcheck
        run: npm run spellcheck
```

3. Save the file and commit it to your repository.

4. In your Ethereum project, make sure you have a `package.json` file with the necessary scripts defined. For example, you can add a `spellcheck` script to run the spellcheck process. Here's an example of how it could be added:

```json
{
  "scripts": {
    "spellcheck": "spellchecker"
  }
}
```

5. Commit the changes to your `package.json` file.

Now, whenever a pull request is opened on the `main` branch of your Ethereum project, the spellcheck workflow will be triggered. It will check for spelling errors in your codebase using the `spellchecker` tool.

Feel free to customize the workflow and the spellcheck script to fit your specific needs.
