### ISSUE TITLE
Reason of allOf usage?

### ISSUE THREAD

**Issue by dapplion** [ethereum/beacon-APIs#233]
Some properties are defined with allOf notation

https://github.com/ethereum/beacon-APIs/blob/9cab46ad3c94a4a2779b42fa21f6bb1955b60b56/types/primitive.yaml#L40-L44

instead of just

```yaml
ExecutionOptimistic: 
   type: boolean 
   example: false 
   description: "True if the response references an unverified execution payload. Optimistic information may be invalidated at a later time. If the field is not present, assume the False value." 
```

The former renders ugly in the final JSON making it harder for tooling to process. Any reason for this? Asking before I do a PR fixing it

```json
                  "title": "GetBlockHeadersResponse",
                  "type": "object",
                  "properties": {
                    "execution_optimistic": {
                      "allOf": [
                        {
                          "type": "boolean"
                        },
                        {
                          "example": false
                        },
                        {
                          "description": "True if the response references an unverified execution payload. Optimistic information may be invalidated at a later time. If the field is not present, assume the False value."
                        }
                      ]
                    },
```
